// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)

// Patientofphysician is the predicate function for patientofphysician builders.
type Patientofphysician func(*sql.Selector)

// Patientroom is the predicate function for patientroom builders.
type Patientroom func(*sql.Selector)

// Physician is the predicate function for physician builders.
type Physician func(*sql.Selector)
