// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/prakaifa21/app/ent/patientofphysician"
	"github.com/prakaifa21/app/ent/patientroom"
)

// PatientroomCreate is the builder for creating a Patientroom entity.
type PatientroomCreate struct {
	config
	mutation *PatientroomMutation
	hooks    []Hook
}

// SetTyperoom sets the Typeroom field.
func (pc *PatientroomCreate) SetTyperoom(s string) *PatientroomCreate {
	pc.mutation.SetTyperoom(s)
	return pc
}

// AddPatientroomIDs adds the Patientroom edge to Patientofphysician by ids.
func (pc *PatientroomCreate) AddPatientroomIDs(ids ...int) *PatientroomCreate {
	pc.mutation.AddPatientroomIDs(ids...)
	return pc
}

// AddPatientroom adds the Patientroom edges to Patientofphysician.
func (pc *PatientroomCreate) AddPatientroom(p ...*Patientofphysician) *PatientroomCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pc.AddPatientroomIDs(ids...)
}

// Mutation returns the PatientroomMutation object of the builder.
func (pc *PatientroomCreate) Mutation() *PatientroomMutation {
	return pc.mutation
}

// Save creates the Patientroom in the database.
func (pc *PatientroomCreate) Save(ctx context.Context) (*Patientroom, error) {
	if _, ok := pc.mutation.Typeroom(); !ok {
		return nil, &ValidationError{Name: "Typeroom", err: errors.New("ent: missing required field \"Typeroom\"")}
	}
	var (
		err  error
		node *Patientroom
	)
	if len(pc.hooks) == 0 {
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PatientroomMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pc.mutation = mutation
			node, err = pc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			mut = pc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PatientroomCreate) SaveX(ctx context.Context) *Patientroom {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pc *PatientroomCreate) sqlSave(ctx context.Context) (*Patientroom, error) {
	pa, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	pa.ID = int(id)
	return pa, nil
}

func (pc *PatientroomCreate) createSpec() (*Patientroom, *sqlgraph.CreateSpec) {
	var (
		pa    = &Patientroom{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: patientroom.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: patientroom.FieldID,
			},
		}
	)
	if value, ok := pc.mutation.Typeroom(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patientroom.FieldTyperoom,
		})
		pa.Typeroom = value
	}
	if nodes := pc.mutation.PatientroomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   patientroom.PatientroomTable,
			Columns: []string{patientroom.PatientroomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patientofphysician.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return pa, _spec
}
