// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/prakaifa21/app/ent/patientofphysician"
	"github.com/prakaifa21/app/ent/physician"
	"github.com/prakaifa21/app/ent/predicate"
)

// PhysicianUpdate is the builder for updating Physician entities.
type PhysicianUpdate struct {
	config
	hooks      []Hook
	mutation   *PhysicianMutation
	predicates []predicate.Physician
}

// Where adds a new predicate for the builder.
func (pu *PhysicianUpdate) Where(ps ...predicate.Physician) *PhysicianUpdate {
	pu.predicates = append(pu.predicates, ps...)
	return pu
}

// SetPhysicianname sets the Physicianname field.
func (pu *PhysicianUpdate) SetPhysicianname(s string) *PhysicianUpdate {
	pu.mutation.SetPhysicianname(s)
	return pu
}

// SetPhysicianemail sets the Physicianemail field.
func (pu *PhysicianUpdate) SetPhysicianemail(s string) *PhysicianUpdate {
	pu.mutation.SetPhysicianemail(s)
	return pu
}

// SetPassword sets the Password field.
func (pu *PhysicianUpdate) SetPassword(s string) *PhysicianUpdate {
	pu.mutation.SetPassword(s)
	return pu
}

// AddPhysicianIDs adds the Physician edge to Patientofphysician by ids.
func (pu *PhysicianUpdate) AddPhysicianIDs(ids ...int) *PhysicianUpdate {
	pu.mutation.AddPhysicianIDs(ids...)
	return pu
}

// AddPhysician adds the Physician edges to Patientofphysician.
func (pu *PhysicianUpdate) AddPhysician(p ...*Patientofphysician) *PhysicianUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pu.AddPhysicianIDs(ids...)
}

// Mutation returns the PhysicianMutation object of the builder.
func (pu *PhysicianUpdate) Mutation() *PhysicianMutation {
	return pu.mutation
}

// RemovePhysicianIDs removes the Physician edge to Patientofphysician by ids.
func (pu *PhysicianUpdate) RemovePhysicianIDs(ids ...int) *PhysicianUpdate {
	pu.mutation.RemovePhysicianIDs(ids...)
	return pu
}

// RemovePhysician removes Physician edges to Patientofphysician.
func (pu *PhysicianUpdate) RemovePhysician(p ...*Patientofphysician) *PhysicianUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pu.RemovePhysicianIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (pu *PhysicianUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(pu.hooks) == 0 {
		affected, err = pu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PhysicianMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pu.mutation = mutation
			affected, err = pu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pu.hooks) - 1; i >= 0; i-- {
			mut = pu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PhysicianUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PhysicianUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PhysicianUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *PhysicianUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   physician.Table,
			Columns: physician.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: physician.FieldID,
			},
		},
	}
	if ps := pu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Physicianname(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: physician.FieldPhysicianname,
		})
	}
	if value, ok := pu.mutation.Physicianemail(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: physician.FieldPhysicianemail,
		})
	}
	if value, ok := pu.mutation.Password(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: physician.FieldPassword,
		})
	}
	if nodes := pu.mutation.RemovedPhysicianIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   physician.PhysicianTable,
			Columns: []string{physician.PhysicianColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patientofphysician.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.PhysicianIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   physician.PhysicianTable,
			Columns: []string{physician.PhysicianColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patientofphysician.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{physician.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// PhysicianUpdateOne is the builder for updating a single Physician entity.
type PhysicianUpdateOne struct {
	config
	hooks    []Hook
	mutation *PhysicianMutation
}

// SetPhysicianname sets the Physicianname field.
func (puo *PhysicianUpdateOne) SetPhysicianname(s string) *PhysicianUpdateOne {
	puo.mutation.SetPhysicianname(s)
	return puo
}

// SetPhysicianemail sets the Physicianemail field.
func (puo *PhysicianUpdateOne) SetPhysicianemail(s string) *PhysicianUpdateOne {
	puo.mutation.SetPhysicianemail(s)
	return puo
}

// SetPassword sets the Password field.
func (puo *PhysicianUpdateOne) SetPassword(s string) *PhysicianUpdateOne {
	puo.mutation.SetPassword(s)
	return puo
}

// AddPhysicianIDs adds the Physician edge to Patientofphysician by ids.
func (puo *PhysicianUpdateOne) AddPhysicianIDs(ids ...int) *PhysicianUpdateOne {
	puo.mutation.AddPhysicianIDs(ids...)
	return puo
}

// AddPhysician adds the Physician edges to Patientofphysician.
func (puo *PhysicianUpdateOne) AddPhysician(p ...*Patientofphysician) *PhysicianUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return puo.AddPhysicianIDs(ids...)
}

// Mutation returns the PhysicianMutation object of the builder.
func (puo *PhysicianUpdateOne) Mutation() *PhysicianMutation {
	return puo.mutation
}

// RemovePhysicianIDs removes the Physician edge to Patientofphysician by ids.
func (puo *PhysicianUpdateOne) RemovePhysicianIDs(ids ...int) *PhysicianUpdateOne {
	puo.mutation.RemovePhysicianIDs(ids...)
	return puo
}

// RemovePhysician removes Physician edges to Patientofphysician.
func (puo *PhysicianUpdateOne) RemovePhysician(p ...*Patientofphysician) *PhysicianUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return puo.RemovePhysicianIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (puo *PhysicianUpdateOne) Save(ctx context.Context) (*Physician, error) {

	var (
		err  error
		node *Physician
	)
	if len(puo.hooks) == 0 {
		node, err = puo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PhysicianMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			puo.mutation = mutation
			node, err = puo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(puo.hooks) - 1; i >= 0; i-- {
			mut = puo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, puo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PhysicianUpdateOne) SaveX(ctx context.Context) *Physician {
	ph, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return ph
}

// Exec executes the query on the entity.
func (puo *PhysicianUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PhysicianUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *PhysicianUpdateOne) sqlSave(ctx context.Context) (ph *Physician, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   physician.Table,
			Columns: physician.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: physician.FieldID,
			},
		},
	}
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Physician.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := puo.mutation.Physicianname(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: physician.FieldPhysicianname,
		})
	}
	if value, ok := puo.mutation.Physicianemail(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: physician.FieldPhysicianemail,
		})
	}
	if value, ok := puo.mutation.Password(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: physician.FieldPassword,
		})
	}
	if nodes := puo.mutation.RemovedPhysicianIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   physician.PhysicianTable,
			Columns: []string{physician.PhysicianColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patientofphysician.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.PhysicianIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   physician.PhysicianTable,
			Columns: []string{physician.PhysicianColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patientofphysician.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	ph = &Physician{config: puo.config}
	_spec.Assign = ph.assignValues
	_spec.ScanValues = ph.scanValues()
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{physician.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return ph, nil
}
