// Code generated by entc, DO NOT EDIT.

package patientroom

const (
	// Label holds the string label denoting the patientroom type in the database.
	Label = "patientroom"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTyperoom holds the string denoting the typeroom field in the database.
	FieldTyperoom = "typeroom"

	// EdgePatientroom holds the string denoting the patientroom edge name in mutations.
	EdgePatientroom = "Patientroom"

	// Table holds the table name of the patientroom in the database.
	Table = "patientrooms"
	// PatientroomTable is the table the holds the Patientroom relation/edge.
	PatientroomTable = "patientofphysicians"
	// PatientroomInverseTable is the table name for the Patientofphysician entity.
	// It exists in this package in order to avoid circular dependency with the "patientofphysician" package.
	PatientroomInverseTable = "patientofphysicians"
	// PatientroomColumn is the table column denoting the Patientroom relation/edge.
	PatientroomColumn = "patientroom_patientroom"
)

// Columns holds all SQL columns for patientroom fields.
var Columns = []string{
	FieldID,
	FieldTyperoom,
}
