// Code generated by entc, DO NOT EDIT.

package patientroom

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/prakaifa21/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Typeroom applies equality check predicate on the "Typeroom" field. It's identical to TyperoomEQ.
func Typeroom(v string) predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTyperoom), v))
	})
}

// TyperoomEQ applies the EQ predicate on the "Typeroom" field.
func TyperoomEQ(v string) predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTyperoom), v))
	})
}

// TyperoomNEQ applies the NEQ predicate on the "Typeroom" field.
func TyperoomNEQ(v string) predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTyperoom), v))
	})
}

// TyperoomIn applies the In predicate on the "Typeroom" field.
func TyperoomIn(vs ...string) predicate.Patientroom {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Patientroom(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldTyperoom), v...))
	})
}

// TyperoomNotIn applies the NotIn predicate on the "Typeroom" field.
func TyperoomNotIn(vs ...string) predicate.Patientroom {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Patientroom(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldTyperoom), v...))
	})
}

// TyperoomGT applies the GT predicate on the "Typeroom" field.
func TyperoomGT(v string) predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTyperoom), v))
	})
}

// TyperoomGTE applies the GTE predicate on the "Typeroom" field.
func TyperoomGTE(v string) predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTyperoom), v))
	})
}

// TyperoomLT applies the LT predicate on the "Typeroom" field.
func TyperoomLT(v string) predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTyperoom), v))
	})
}

// TyperoomLTE applies the LTE predicate on the "Typeroom" field.
func TyperoomLTE(v string) predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTyperoom), v))
	})
}

// TyperoomContains applies the Contains predicate on the "Typeroom" field.
func TyperoomContains(v string) predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldTyperoom), v))
	})
}

// TyperoomHasPrefix applies the HasPrefix predicate on the "Typeroom" field.
func TyperoomHasPrefix(v string) predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldTyperoom), v))
	})
}

// TyperoomHasSuffix applies the HasSuffix predicate on the "Typeroom" field.
func TyperoomHasSuffix(v string) predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldTyperoom), v))
	})
}

// TyperoomEqualFold applies the EqualFold predicate on the "Typeroom" field.
func TyperoomEqualFold(v string) predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldTyperoom), v))
	})
}

// TyperoomContainsFold applies the ContainsFold predicate on the "Typeroom" field.
func TyperoomContainsFold(v string) predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldTyperoom), v))
	})
}

// HasPatientroom applies the HasEdge predicate on the "Patientroom" edge.
func HasPatientroom() predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PatientroomTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PatientroomTable, PatientroomColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPatientroomWith applies the HasEdge predicate on the "Patientroom" edge with a given conditions (other predicates).
func HasPatientroomWith(preds ...predicate.Patientofphysician) predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PatientroomInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PatientroomTable, PatientroomColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Patientroom) predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Patientroom) predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Patientroom) predicate.Patientroom {
	return predicate.Patientroom(func(s *sql.Selector) {
		p(s.Not())
	})
}
