// Code generated by entc, DO NOT EDIT.

package patientofphysician

const (
	// Label holds the string label denoting the patientofphysician type in the database.
	Label = "patientofphysician"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAilment holds the string denoting the ailment field in the database.
	FieldAilment = "ailment"

	// EdgeIdpatient holds the string denoting the idpatient edge name in mutations.
	EdgeIdpatient = "Idpatient"
	// EdgeRoomid holds the string denoting the roomid edge name in mutations.
	EdgeRoomid = "Roomid"
	// EdgeIdphysicianid holds the string denoting the idphysicianid edge name in mutations.
	EdgeIdphysicianid = "Idphysicianid"

	// Table holds the table name of the patientofphysician in the database.
	Table = "patientofphysicians"
	// IdpatientTable is the table the holds the Idpatient relation/edge.
	IdpatientTable = "patientofphysicians"
	// IdpatientInverseTable is the table name for the Patient entity.
	// It exists in this package in order to avoid circular dependency with the "patient" package.
	IdpatientInverseTable = "patients"
	// IdpatientColumn is the table column denoting the Idpatient relation/edge.
	IdpatientColumn = "patient_patient"
	// RoomidTable is the table the holds the Roomid relation/edge.
	RoomidTable = "patientofphysicians"
	// RoomidInverseTable is the table name for the Patientroom entity.
	// It exists in this package in order to avoid circular dependency with the "patientroom" package.
	RoomidInverseTable = "patientrooms"
	// RoomidColumn is the table column denoting the Roomid relation/edge.
	RoomidColumn = "patientroom_patientroom"
	// IdphysicianidTable is the table the holds the Idphysicianid relation/edge.
	IdphysicianidTable = "patientofphysicians"
	// IdphysicianidInverseTable is the table name for the Physician entity.
	// It exists in this package in order to avoid circular dependency with the "physician" package.
	IdphysicianidInverseTable = "physicians"
	// IdphysicianidColumn is the table column denoting the Idphysicianid relation/edge.
	IdphysicianidColumn = "physician_physician"
)

// Columns holds all SQL columns for patientofphysician fields.
var Columns = []string{
	FieldID,
	FieldAilment,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Patientofphysician type.
var ForeignKeys = []string{
	"patient_patient",
	"patientroom_patientroom",
	"physician_physician",
}
