// Code generated by entc, DO NOT EDIT.

package patientofphysician

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/prakaifa21/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Ailment applies equality check predicate on the "Ailment" field. It's identical to AilmentEQ.
func Ailment(v string) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAilment), v))
	})
}

// AilmentEQ applies the EQ predicate on the "Ailment" field.
func AilmentEQ(v string) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAilment), v))
	})
}

// AilmentNEQ applies the NEQ predicate on the "Ailment" field.
func AilmentNEQ(v string) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldAilment), v))
	})
}

// AilmentIn applies the In predicate on the "Ailment" field.
func AilmentIn(vs ...string) predicate.Patientofphysician {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Patientofphysician(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldAilment), v...))
	})
}

// AilmentNotIn applies the NotIn predicate on the "Ailment" field.
func AilmentNotIn(vs ...string) predicate.Patientofphysician {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Patientofphysician(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldAilment), v...))
	})
}

// AilmentGT applies the GT predicate on the "Ailment" field.
func AilmentGT(v string) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldAilment), v))
	})
}

// AilmentGTE applies the GTE predicate on the "Ailment" field.
func AilmentGTE(v string) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldAilment), v))
	})
}

// AilmentLT applies the LT predicate on the "Ailment" field.
func AilmentLT(v string) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldAilment), v))
	})
}

// AilmentLTE applies the LTE predicate on the "Ailment" field.
func AilmentLTE(v string) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldAilment), v))
	})
}

// AilmentContains applies the Contains predicate on the "Ailment" field.
func AilmentContains(v string) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldAilment), v))
	})
}

// AilmentHasPrefix applies the HasPrefix predicate on the "Ailment" field.
func AilmentHasPrefix(v string) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldAilment), v))
	})
}

// AilmentHasSuffix applies the HasSuffix predicate on the "Ailment" field.
func AilmentHasSuffix(v string) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldAilment), v))
	})
}

// AilmentEqualFold applies the EqualFold predicate on the "Ailment" field.
func AilmentEqualFold(v string) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldAilment), v))
	})
}

// AilmentContainsFold applies the ContainsFold predicate on the "Ailment" field.
func AilmentContainsFold(v string) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldAilment), v))
	})
}

// HasIdpatient applies the HasEdge predicate on the "Idpatient" edge.
func HasIdpatient() predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(IdpatientTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, IdpatientTable, IdpatientColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIdpatientWith applies the HasEdge predicate on the "Idpatient" edge with a given conditions (other predicates).
func HasIdpatientWith(preds ...predicate.Patient) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(IdpatientInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, IdpatientTable, IdpatientColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRoomid applies the HasEdge predicate on the "Roomid" edge.
func HasRoomid() predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RoomidTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RoomidTable, RoomidColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoomidWith applies the HasEdge predicate on the "Roomid" edge with a given conditions (other predicates).
func HasRoomidWith(preds ...predicate.Patientroom) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RoomidInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RoomidTable, RoomidColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasIdphysicianid applies the HasEdge predicate on the "Idphysicianid" edge.
func HasIdphysicianid() predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(IdphysicianidTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, IdphysicianidTable, IdphysicianidColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIdphysicianidWith applies the HasEdge predicate on the "Idphysicianid" edge with a given conditions (other predicates).
func HasIdphysicianidWith(preds ...predicate.Physician) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(IdphysicianidInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, IdphysicianidTable, IdphysicianidColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Patientofphysician) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Patientofphysician) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Patientofphysician) predicate.Patientofphysician {
	return predicate.Patientofphysician(func(s *sql.Selector) {
		p(s.Not())
	})
}
