// Code generated by entc, DO NOT EDIT.

package physician

const (
	// Label holds the string label denoting the physician type in the database.
	Label = "physician"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPhysicianname holds the string denoting the physicianname field in the database.
	FieldPhysicianname = "physicianname"
	// FieldPhysicianemail holds the string denoting the physicianemail field in the database.
	FieldPhysicianemail = "physicianemail"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"

	// EdgePhysician holds the string denoting the physician edge name in mutations.
	EdgePhysician = "Physician"

	// Table holds the table name of the physician in the database.
	Table = "physicians"
	// PhysicianTable is the table the holds the Physician relation/edge.
	PhysicianTable = "patientofphysicians"
	// PhysicianInverseTable is the table name for the Patientofphysician entity.
	// It exists in this package in order to avoid circular dependency with the "patientofphysician" package.
	PhysicianInverseTable = "patientofphysicians"
	// PhysicianColumn is the table column denoting the Physician relation/edge.
	PhysicianColumn = "physician_physician"
)

// Columns holds all SQL columns for physician fields.
var Columns = []string{
	FieldID,
	FieldPhysicianname,
	FieldPhysicianemail,
	FieldPassword,
}
