/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersPatientofphysician
 */
export interface ControllersPatientofphysician {
    /**
     * 
     * @type {string}
     * @memberof ControllersPatientofphysician
     */
    ailment?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersPatientofphysician
     */
    patientID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersPatientofphysician
     */
    physicianID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersPatientofphysician
     */
    roomID?: number;
}

export function ControllersPatientofphysicianFromJSON(json: any): ControllersPatientofphysician {
    return ControllersPatientofphysicianFromJSONTyped(json, false);
}

export function ControllersPatientofphysicianFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersPatientofphysician {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ailment': !exists(json, 'ailment') ? undefined : json['ailment'],
        'patientID': !exists(json, 'patientID') ? undefined : json['patientID'],
        'physicianID': !exists(json, 'physicianID') ? undefined : json['physicianID'],
        'roomID': !exists(json, 'roomID') ? undefined : json['roomID'],
    };
}

export function ControllersPatientofphysicianToJSON(value?: ControllersPatientofphysician | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ailment': value.ailment,
        'patientID': value.patientID,
        'physicianID': value.physicianID,
        'roomID': value.roomID,
    };
}


