/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPhysicianEdges,
    EntPhysicianEdgesFromJSON,
    EntPhysicianEdgesFromJSONTyped,
    EntPhysicianEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPhysician
 */
export interface EntPhysician {
    /**
     * Password holds the value of the "Password" field.
     * @type {string}
     * @memberof EntPhysician
     */
    password?: string;
    /**
     * Physicianemail holds the value of the "Physicianemail" field.
     * @type {string}
     * @memberof EntPhysician
     */
    physicianemail?: string;
    /**
     * Physicianname holds the value of the "Physicianname" field.
     * @type {string}
     * @memberof EntPhysician
     */
    physicianname?: string;
    /**
     * 
     * @type {EntPhysicianEdges}
     * @memberof EntPhysician
     */
    edges?: EntPhysicianEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntPhysician
     */
    id?: number;
}

export function EntPhysicianFromJSON(json: any): EntPhysician {
    return EntPhysicianFromJSONTyped(json, false);
}

export function EntPhysicianFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPhysician {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'password': !exists(json, 'Password') ? undefined : json['Password'],
        'physicianemail': !exists(json, 'Physicianemail') ? undefined : json['Physicianemail'],
        'physicianname': !exists(json, 'Physicianname') ? undefined : json['Physicianname'],
        'edges': !exists(json, 'edges') ? undefined : EntPhysicianEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntPhysicianToJSON(value?: EntPhysician | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Password': value.password,
        'Physicianemail': value.physicianemail,
        'Physicianname': value.physicianname,
        'edges': EntPhysicianEdgesToJSON(value.edges),
        'id': value.id,
    };
}


