/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPatient,
    EntPatientFromJSON,
    EntPatientFromJSONTyped,
    EntPatientToJSON,
    EntPatientroom,
    EntPatientroomFromJSON,
    EntPatientroomFromJSONTyped,
    EntPatientroomToJSON,
    EntPhysician,
    EntPhysicianFromJSON,
    EntPhysicianFromJSONTyped,
    EntPhysicianToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPatientofphysicianEdges
 */
export interface EntPatientofphysicianEdges {
    /**
     * 
     * @type {EntPatient}
     * @memberof EntPatientofphysicianEdges
     */
    idpatient?: EntPatient;
    /**
     * 
     * @type {EntPhysician}
     * @memberof EntPatientofphysicianEdges
     */
    idphysicianid?: EntPhysician;
    /**
     * 
     * @type {EntPatientroom}
     * @memberof EntPatientofphysicianEdges
     */
    roomid?: EntPatientroom;
}

export function EntPatientofphysicianEdgesFromJSON(json: any): EntPatientofphysicianEdges {
    return EntPatientofphysicianEdgesFromJSONTyped(json, false);
}

export function EntPatientofphysicianEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPatientofphysicianEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'idpatient': !exists(json, 'Idpatient') ? undefined : EntPatientFromJSON(json['Idpatient']),
        'idphysicianid': !exists(json, 'Idphysicianid') ? undefined : EntPhysicianFromJSON(json['Idphysicianid']),
        'roomid': !exists(json, 'Roomid') ? undefined : EntPatientroomFromJSON(json['Roomid']),
    };
}

export function EntPatientofphysicianEdgesToJSON(value?: EntPatientofphysicianEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'idpatient': EntPatientToJSON(value.idpatient),
        'idphysicianid': EntPhysicianToJSON(value.idphysicianid),
        'roomid': EntPatientroomToJSON(value.roomid),
    };
}


