/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPatientofphysician,
    EntPatientofphysicianFromJSON,
    EntPatientofphysicianFromJSONTyped,
    EntPatientofphysicianToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPatientroomEdges
 */
export interface EntPatientroomEdges {
    /**
     * Patientroom holds the value of the Patientroom edge.
     * @type {Array<EntPatientofphysician>}
     * @memberof EntPatientroomEdges
     */
    patientroom?: Array<EntPatientofphysician>;
}

export function EntPatientroomEdgesFromJSON(json: any): EntPatientroomEdges {
    return EntPatientroomEdgesFromJSONTyped(json, false);
}

export function EntPatientroomEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPatientroomEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patientroom': !exists(json, 'patientroom') ? undefined : ((json['patientroom'] as Array<any>).map(EntPatientofphysicianFromJSON)),
    };
}

export function EntPatientroomEdgesToJSON(value?: EntPatientroomEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patientroom': value.patientroom === undefined ? undefined : ((value.patientroom as Array<any>).map(EntPatientofphysicianToJSON)),
    };
}


